config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :contacts
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :contact, required: false
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    has_many :phones, dependent: :destroy # possui muitos phones
    has_one :address, dependent: :destroy # possui um address

    has_many :contact_kinds # possui muitos
    has_many :kinds, through: :contact_kind # possui muitos kinds, através de

    accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true
    accepts_nested_attributes_for :address
end

app/models/contact_kind.rb
class ContactKind < ApplicationRecord
  belongs_to :contact
  belongs_to :kind
end

app/models/kind.rb
class Kind < ApplicationRecord
    has_many :contact_kinds # possui muitos de
    has_many :contacts, through: :contact_kinds # possui muitos conctacts, através de
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact, required: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  
  def index
    @contacts = Contact.all
  end

  def show
  end

  def new
    @contact = Contact.new
    @contact.build_address
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to contacts_path
    else
      render :new, notice: 'Não foi possível criar um novo contato'
    end
  end

  def edit
  end

  def update
    if @contact.update(contact_params)
      redirect_to contacts_path
    else
      render :new, notice: 'Não foi possível editar o contato'
    end
  end

  def destroy
    @contact.destroy
    redirect_to contacts_path
  end

  private

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(
      :name,
      phones_attributes: [:number, :id],
      address_attributes: [:street, :number, :neighborhood]
      )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for @contact do |form| %>
    <% if @contact.errors.any? %>
    <div id="error">
        <h2><%= pluralize(@contact.errors.count, "error") %> Error on save contact:</h2>
        <ul>
        <% @contact.errors.full_messages.each do |e| %>
            <li><%= e %></li>
        <% end %>
    </div>
    <% end %>
    
    <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <h4>Address</h4>

    <%= form.fields_for :address do |a| %>
        <div class="field">
            <%= a.label :street %>
            <%= a.text_field :street %>
        </div>

        <div class="field">
            <%= a.label :number %>
            <%= a.text_field :number %>
        </div>

        <div class="field">
            <%= a.label :neighborhood %>
            <%= a.text_field :neighborhood %>
        </div>
    <% end %>
    
    <h4>Phones</h4>
    
    <div id='phones'>
        <%= form.fields_for :phones do |p| %>
            <%= render 'phone_fields', :f => p %>
        <% end %>
        <div class='links'>
            <%= link_to_add_association 'add phone', form, :phones %>
        </div>
    </div>
    
    </br>            

    <div class="actions">
        <%= form.submit 'Save' %>
    </div>
<% end %>

app/views/contacts/_phone_fields.html.erb
<div class='nested-fields'>
    <div class="field">
        <%= f.label :number %>
        <%= f.text_field :number %>
    </div>
    <%= link_to_remove_association "remove phone", f %>
</div>

app/views/contacts/edit.html.erb
<h1>Edit Contact</h1>
<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<table>
    <thead>
        <tr>
            <td>Id</td>
            <td>Name</td>
            <td>Actions</td>
        </tr>
    </thead>
    <tbody>
    <% @contacts.each do |c| %>
        <tr>
            <td><%= c.id %></td>
            <td><%= c.name %></td>
            <td>
                <%= link_to 'Show', c %>
                <%= link_to 'Edit', edit_contact_path(c) %>
                <%= link_to 'Destroy', c, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
        </tr>
    <% end %>
    </tbody>
</table>



<%= link_to 'New', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>
<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<h1>Contacts#show</h1>
<p>Id: <%= @contact.id %></p>
<p>Name: <%= @contact.name %></p>

<h3>Address</h3>
<p>Street: <%= @contact.address.street %></p>
<p>Number: <%= @contact.address.number %></p>
<p>Neighborhood: <%= @contact.address.neighborhood %></p>

<h3>Phones</h3>
<ol>
    <% @contact.phones.each do |p| %>  
        <li><%= p.number %></li>
    <% end %>
</ol>
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agenda</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>